# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title-bold: Brown
title-normal: Base Camp
email: brown_institute@stanford.edu
description: Are you passionate about the role that emerging technologies can play in the future of storytelling and journalism? Do you have a story that can only be told using technology outside the scope of traditional media? <br/><br/> Funding for projects ranges up to $150,000 for Stanford or Columbia teams and up to $300,000 for bicoastal teams. <br/><br/> <strong>Applications due December 4</strong>

# Local
# baseurl:
# url:

# Public
baseurl: basecamp
url: https://browninstitute.github.io/

fall-date: November 12-13, 2016
fall-location: Columbia University
fall-city: New York
fall-state: NY

winter-date: January 14-15, 2017
winter-location: Stanford University
winter-city: Stanford
winter-state: CA

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url: https://www.facebook.com/MadeAtBrown/
github_url: https://github.com/browninstitute
slack_url:
twitter_url: https://twitter.com/browninstitute

# Build settings
markdown: kramdown

# Plugin: jekyll-seo-tag
twitter:
  username: browninstitute
# Add one or more of the following
facebook:
  app_id:
  publisher:
  admins:
logo:
google_site_verification:
